name: CI
on:
  push:
    branches: [main]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  runtimes_node:
    name: Node
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Run Audit
        run: npm audit --omit=dev --audit-level=moderate
      - name: Run Lint
        run: npm run lint
      - name: Run Types
        run: npm run types
  runtimes_bun:
    name: Bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: bun install
      - name: Run Audit
        run: bun audit
      - name: Run Lint
        run: npm run lint
      - name: Run Types
        run: npm run types
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: [runtimes_node, runtimes_bun]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org/'
      - name: Install Dependencies
        run: npm ci
      - name: Prepare distribution
        run: |
          rm -rf ./dist
          mkdir ./dist
          npx tsc -p ./tsconfig.build.json
          npx tsc -p ./tsconfig.types.json
          npx tsc -p ./tsconfig.types_all.json
          cp package.json README.md LICENSE.md .npmignore ./dist
          cp ./lib/modules/JSX/jsx.d.ts ./dist/modules/JSX/jsx.d.ts
          cp ./lib/jsx-runtime.d.ts ./dist/jsx-runtime.d.ts
      - name: Publish to npm
        run: |
          cd ./dist
          npm publish --access public --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
