name: Lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [node-20, node-22, bun]
    steps:
    - uses: actions/checkout@v3
    - name: Setup runtime
      if: startsWith(matrix.runtime, 'node')
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.runtime == 'node-20' && '20' || '22' }}
        cache: 'npm'
    - name: Setup Bun
      if: matrix.runtime == 'bun'
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - name: Install dependencies
      run: |
        if [[ "${{ matrix.runtime }}" == "bun" ]]; then
          bun install
        else
          npm ci
        fi
    - name: Run lint
      run: npm run lint